[package]
name = "simple_client"
version = "0.1.0"
edition = "2021"

[dependencies]
wow_login_messages = { path = "../wow_login_messages", features = ["sync"] }
wow_vanilla_messages = { path = "../wow_vanilla_messages", features = ["sync"] }
wow_srp = { version = "0.4.0" }
