[workspace]

members = [
    "tbc_server",
    "vanilla_client",
    "vanilla_server",
    "wow_message_parser",
    "wow_world_messages",
    "wow_world_base",
    "wow_login_messages",
    "wrath_server",
]
