spec = "WoW 1.12 MESSAGE DESCRIPTION FORMAT"
version = "0.1.0"

[fields.opcode]
type = "u8"
comment = "0x00 for CMD_AUTH_LOGON_CHALLENGE\n 0x02 for CMD_AUTH_RECONNECT_CHALLENGE"

[fields.protocol_version]
type = "u8"
comment = "Exact purpose unknown. See table in #Protocol Versions."

[fields.game_name]
type = ["u8", 4]
endianness = "big"
comment = "Always null terminated \"WoW\\0\" string."

[fields.version]
type = ["u8", 3]
endianness = "little"
comment = "[0x01, 0x01, 0x02] for 1.1.2. [0x01, 0x0C, 0x01] for 1.12.1."

[fields.build]
type = "u16"
endianness = "little"
comment = "4125, aka [[Rev|Revision]]"

[fields.platform]
type = ["u8", 4]
endianness = "little"
comment = "eg '\\0x86'. Has a leading zero for 'x86'."

[fields.os]
type = ["u8", 4]
endianness = "little"
comment = "eg '\\0Win'. Has a leading zero for 'Win'."


