[package]
name = "wow_world_base"
version = "0.1.0"
edition = "2018"

[features]
extended = []
vanilla = []
tbc = []
wrath = []

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
