[package]
name = "vanilla_client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
wow_login_messages = { path = "../../wow_login_messages", features = ["sync"] }
wow_world_messages = { path = "../../wow_world_messages", features = ["sync", "vanilla"] }

[dependencies.wow_srp]
git = "https://github.com/gtker/wow_srp.git"
rev = "ba56b4564ec9f7baf6bec824e547e9279a0f58ce"
